package stashvision

var PoeItemClassesToNames = make(map[string][]string)
var PoeItemNamesToClasses = make(map[string]string)

func init() {
    PoeItemClassesToNames["Amulet"] = []string{
        "Lapis Amulet",
        "Marble Amulet",
        "Avian Twins Talisman",
        "Deadhand Talisman",
        "Onyx Amulet",
        "Blue Pearl Amulet",
        "Breakrib Talisman",
        "Gold Amulet",
        "Spinefuse Talisman",
        "Ruby Amulet",
        "Writhing Talisman",
        "Jet Amulet",
        "Horned Talisman",
        "Longtooth Talisman",
        "Coral Amulet",
        "Three Rat Talisman",
        "Monkey Paw Talisman",
        "Bonespire Talisman",
        "Ashscale Talisman",
        "Wereclaw Talisman",
        "Rotfeather Talisman",
        "Fangjaw Talisman",
        "Amber Amulet",
        "Agate Amulet",
        "Three Hands Talisman",
        "Jade Amulet",
        "Citrine Amulet",
        "Lone Antler Talisman",
        "Rot Head Talisman",
        "Paua Amulet",
        "Clutching Talisman",
        "Monkey Twins Talisman",
        "Mandible Talisman",
        "Undying Flesh Talisman",
        "Turquoise Amulet",
        "Splitnewt Talisman",
        "Deep One Talisman",
        "Primal Skull Talisman",
        "Black Maw Talisman",
        "Greatwolf Talisman",
        "Hexclaw Talisman",
        "Chrysalis Talisman",
    }
    PoeItemClassesToNames["Belt"] = []string{
        "Studded Belt",
        "Rustic Sash",
        "Stygian Vise",
        "Vanguard Belt",
        "Crystal Belt",
        "Golden Obi",
        "Cloth Belt",
        "Heavy Belt",
        "Leather Belt",
        "Chain Belt",
    }
    PoeItemClassesToNames["Boots"] = []string{
        "Deerskin Boots",
        "Nubuck Boots",
        "Eelskin Boots",
        "Golden Caligae",
        "Wrapped Boots",
        "Crusader Boots",
        "Shagreen Boots",
        "Conjurer Boots",
        "Titan Greaves",
        "Dragonscale Boots",
        "Rawhide Boots",
        "Riveted Boots",
        "Leatherscale Boots",
        "Zealot Boots",
        "Stealth Boots",
        "Avian Slippers",
        "Goathide Boots",
        "Clasped Boots",
        "Kaom's Greaves",
        "Carnal Boots",
        "Iron Greaves",
        "Mesh Boots",
        "Arcanist Slippers",
        "Two-Toned Boots",
        "Samite Slippers",
        "Wyrmscale Boots",
        "Ringmail Boots",
        "Slink Boots",
        "Silk Slippers",
        "Sharkskin Boots",
        "Ironscale Boots",
        "Wool Shoes",
        "Murder Boots",
        "Velvet Slippers",
        "Serpentscale Boots",
        "Bronzescale Boots",
        "Satin Slippers",
        "Strapped Boots",
        "Ambush Boots",
        "Assassin's Boots",
        "Steelscale Boots",
        "Legion Boots",
        "Chain Boots",
        "Goliath Greaves",
        "Plated Greaves",
        "Sorcerer Boots",
        "Vaal Greaves",
        "Soldier Boots",
        "Ancient Greaves",
        "Scholar Boots",
        "Hydrascale Boots",
        "Steel Greaves",
        "Shackled Boots",
        "Reinforced Greaves",
        "Trapper Boots",
        "Antique Greaves",
    }
    PoeItemClassesToNames["Bow"] = []string{
        "Ivory Bow",
        "Steelwood Bow",
        "Thicket Bow",
        "Citadel Bow",
        "Imperial Bow",
        "Long Bow",
        "Bone Bow",
        "Death Bow",
        "Ranger Bow",
        "Maraketh Bow",
        "Decimation Bow",
        "Decurve Bow",
        "Reflex Bow",
        "Spine Bow",
        "Highborn Bow",
        "Recurve Bow",
        "Composite Bow",
        "Grove Bow",
        "Short Bow",
        "Crude Bow",
        "Assassin Bow",
        "Royal Bow",
        "Compound Bow",
        "Harbinger Bow",
        "Sniper Bow",
    }
    PoeItemClassesToNames["Body Armour"] = []string{
        "Crusader Chainmail",
        "Full Leather",
        "Conjurer's Vestment",
        "Assassin's Garb",
        "Destiny Leather",
        "Quilted Jacket",
        "Silk Robe",
        "Holy Chainmail",
        "Full Ringmail",
        "Sharkskin Tunic",
        "Frontier Leather",
        "Gladiator Plate",
        "Chainmail Vest",
        "Bone Armour",
        "Coronal Leather",
        "Padded Vest",
        "Full Scale Armour",
        "Sadist Garb",
        "Scale Doublet",
        "Cutthroat's Garb",
        "Lacquered Garb",
        "Elegant Ringmail",
        "Vaal Regalia",
        "Full Plate",
        "Light Brigandine",
        "Soldier's Brigandine",
        "Field Lamellar",
        "Scarlet Raiment",
        "General's Brigandine",
        "Occultist's Vestment",
        "Glorious Leather",
        "Simple Robe",
        "Chainmail Doublet",
        "Ringmail Coat",
        "Saint's Hauberk",
        "Chainmail Tunic",
        "Plate Vest",
        "Sun Plate",
        "Glorious Plate",
        "Necromancer Silks",
        "Conquest Chainmail",
        "Strapped Leather",
        "Kaom's Plate",
        "Commander's Brigandine",
        "Destroyer Regalia",
        "Blood Raiment",
        "Hussar Brigandine",
        "Wyrmscale Doublet",
        "Copper Plate",
        "Crypt Armour",
        "Thief's Garb",
        "Full Dragonscale",
        "Scale Vest",
        "Waxed Garb",
        "Savant's Robe",
        "Silken Garb",
        "Oiled Coat",
        "Mage's Vestment",
        "Colosseum Plate",
        "Golden Plate",
        "Varnished Coat",
        "Battle Lamellar",
        "Crimson Raiment",
        "Scholar's Robe",
        "Cabalist Regalia",
        "Bronze Plate",
        "Spidersilk Robe",
        "Exquisite Leather",
        "Padded Jacket",
        "Lordly Plate",
        "Desert Brigandine",
        "Full Chainmail",
        "Chestplate",
        "Full Wyrmscale",
        "Buckskin Tunic",
        "Widowsilk Robe",
        "Zodiac Leather",
        "Carnal Armour",
        "Majestic Plate",
        "Devout Chainmail",
        "Golden Mantle",
        "Latticed Ringmail",
        "Sage's Robe",
        "Saintly Chainmail",
        "War Plate",
        "Crusader Plate",
        "Dragonscale Doublet",
        "Loricated Ringmail",
        "Triumphant Lamellar",
        "Battle Plate",
        "Infantry Brigandine",
        "Arena Plate",
        "Sleek Coat",
        "Eelskin Tunic",
        "Silken Vest",
        "Sun Leather",
        "Sacrificial Garb",
        "Chain Hauberk",
        "Sentinel Jacket",
        "Ornate Ringmail",
        "Oiled Vest",
        "Shabby Jerkin",
        "Wild Leather",
        "Astral Plate",
        "Silken Wrap",
    }
    PoeItemClassesToNames["Claw"] = []string{
        "Great White Claw",
        "Gut Ripper",
        "Nailed Fist",
        "Timeworn Claw",
        "Twin Claw",
        "Noble Claw",
        "Throat Stabber",
        "Fright Claw",
        "Terror Claw",
        "Vaal Claw",
        "Eagle Claw",
        "Hellion's Paw",
        "Awl",
        "Cat's Paw",
        "Prehistoric Claw",
        "Sparkling Claw",
        "Double Claw",
        "Thresher Claw",
        "Blinder",
        "Eye Gouger",
        "Gemini Claw",
        "Gouger",
        "Imperial Claw",
        "Tiger's Paw",
        "Sharktooth Claw",
    }
    PoeItemClassesToNames["Dagger"] = []string{
        "Flaying Knife",
        "Sai",
        "Poignard",
        "Prong Dagger",
        "Stiletto",
        "Glass Shank",
        "Skinning Knife",
        "Gutting Knife",
        "Ambusher",
        "Trisula",
    }
    PoeItemClassesToNames["Gloves"] = []string{
        "Vaal Gauntlets",
        "Velvet Gloves",
        "Goliath Gauntlets",
        "Zealot Gloves",
        "Hydrascale Gauntlets",
        "Steel Gauntlets",
        "Spiked Gloves",
        "Ambush Mitts",
        "Arcanist Gloves",
        "Chain Gloves",
        "Murder Mitts",
        "Gripped Gloves",
        "Legion Gloves",
        "Trapper Mitts",
        "Embroidered Gloves",
        "Stealth Gloves",
        "Bronzescale Gauntlets",
        "Fingerless Silk Gloves",
        "Sorcerer Gloves",
        "Mesh Gloves",
        "Titan Gauntlets",
        "Plated Gauntlets",
        "Crusader Gloves",
        "Rawhide Gloves",
        "Strapped Mitts",
        "Dragonscale Gauntlets",
        "Antique Gauntlets",
        "Eelskin Gloves",
        "Riveted Gloves",
        "Golden Bracers",
        "Bronze Gauntlets",
        "Samite Gloves",
        "Slink Gloves",
        "Satin Gloves",
        "Iron Gauntlets",
        "Ancient Gauntlets",
        "Serpentscale Gauntlets",
        "Deerskin Gloves",
        "Carnal Mitts",
        "Sharkskin Gloves",
        "Wool Gloves",
        "Silk Gloves",
        "Shagreen Gloves",
        "Conjurer Gloves",
        "Wyrmscale Gauntlets",
        "Assassin's Mitts",
        "Soldier Gloves",
        "Fishscale Gauntlets",
        "Wrapped Mitts",
        "Nubuck Gloves",
        "Clasped Mitts",
        "Ironscale Gauntlets",
        "Steelscale Gauntlets",
        "Goathide Gloves",
        "Ringmail Gloves",
    }
    PoeItemClassesToNames["Helmet"] = []string{
        "Leather Cap",
        "Leather Hood",
        "Iron Mask",
        "Sallet",
        "Prophet Crown",
        "Secutor Helm",
        "Great Helmet",
        "Sinner Tricorne",
        "Royal Burgonet",
        "Callous Mask",
        "Lunaris Circlet",
        "Zealot Helmet",
        "Reaver Helmet",
        "Visored Sallet",
        "Bone Circlet",
        "Deicide Mask",
        "Close Helmet",
        "Bone Helmet",
        "Silken Hood",
        "Iron Hat",
        "Nightmare Bascinet",
        "Battered Helm",
        "Lacquered Helmet",
        "Vaal Mask",
        "Golden Mask",
        "Pig-Faced Bascinet",
        "Soldier Helmet",
        "Mind Cage",
        "Crusader Helmet",
        "Regicide Mask",
        "Hunter Hood",
        "Steel Circlet",
        "Vine Circlet",
        "Scare Mask",
        "Golden Wreath",
        "Necromancer Circlet",
        "Lion Pelt",
        "Magistrate Crown",
        "Tricorne",
        "Ursine Pelt",
        "Plague Mask",
        "Solaris Circlet",
        "Ezomyte Burgonet",
        "Rusted Coif",
        "Samite Helmet",
        "Harlequin Mask",
        "Wolf Pelt",
        "Fluted Bascinet",
        "Aventail Helmet",
        "Golden Visage",
        "Cone Helmet",
        "Siege Helmet",
        "Noble Tricorne",
        "Festival Mask",
        "Barbute Helmet",
        "Iron Circlet",
        "Raven Mask",
        "Hubris Circlet",
        "Gladiator Helmet",
        "Fencer Helm",
        "Praetor Crown",
        "Gilded Sallet",
        "Great Crown",
        "Eternal Burgonet",
        "Torture Cage",
        "Tribal Circlet",
    }
    PoeItemClassesToNames["One Hand Axe"] = []string{
        "Etched Hatchet",
        "Ceremonial Axe",
        "Karui Axe",
        "Reaver Axe",
        "Broad Axe",
        "Tomahawk",
        "Runic Hatchet",
        "Infernal Axe",
        "Wrist Chopper",
        "Royal Axe",
        "Boarding Axe",
        "Butcher Axe",
        "Wraith Axe",
        "Rusted Hatchet",
        "War Axe",
        "Arming Axe",
        "Vaal Hatchet",
        "Cleaver",
        "Chest Splitter",
        "Jasper Axe",
        "Engraved Hatchet",
        "Decorative Axe",
        "Siege Axe",
        "Jade Hatchet",
        "Spectral Axe",
    }
    PoeItemClassesToNames["One Hand Mace"] = []string{
        "Gavel",
        "Rock Breaker",
        "War Hammer",
        "Stone Hammer",
        "Phantom Mace",
        "Nightmare Mace",
        "Wyrm Mace",
        "Spiked Club",
        "Barbed Club",
        "Battle Hammer",
        "Pernarch",
        "Behemoth Mace",
        "Auric Mace",
        "Ornate Mace",
        "Tenderizer",
        "Dragon Mace",
        "Legion Hammer",
        "Ancestral Club",
        "Flanged Mace",
        "Bladed Mace",
        "Dream Mace",
        "Petrified Club",
        "Ceremonial Mace",
        "Tribal Club",
        "Driftwood Club",
    }
    PoeItemClassesToNames["One Hand Sword"] = []string{
        "Battle Sword",
        "Graceful Sword",
        "Tiger Hook",
        "Vaal Blade",
        "Legion Sword",
        "Ancient Sword",
        "Grappler",
        "Gemstone Sword",
        "Midnight Blade",
        "Elder Sword",
        "Copper Sword",
        "War Sword",
        "Charan's Sword",
        "Twilight Blade",
        "Broad Sword",
        "Rusted Sword",
        "Variscite Blade",
        "Corsair Sword",
        "Baselard",
        "Sabre",
        "Elegant Sword",
        "Dusk Blade",
        "Gladius",
        "Eternal Sword",
        "Hook Sword",
        "Cutlass",
    }
    PoeItemClassesToNames["Quiver"] = []string{
        "Sharktooth Arrow Quiver",
        "Heavy Quiver",
        "Ornate Quiver",
        "Serrated Arrow Quiver",
        "Two-Point Arrow Quiver",
        "Fire Arrow Quiver",
        "Penetrating Arrow Quiver",
        "Rugged Quiver",
        "Blunt Arrow Quiver",
        "Cured Quiver",
        "Light Quiver",
        "Spike-Point Arrow Quiver",
        "Broadhead Arrow Quiver",
        "Conductive Quiver",
    }
    PoeItemClassesToNames["Ring"] = []string{
        "Diamond Ring",
        "Paua Ring",
        "Unset Ring",
        "Vermillion Ring",
        "Prismatic Ring",
        "Amethyst Ring",
        "Coral Ring",
        "Gold Ring",
        "Sapphire Ring",
        "Golden Hoop",
        "Breach Ring",
        "Steel Ring",
        "Topaz Ring",
        "Moonstone Ring",
        "Two-Stone Ring",
        "Ruby Ring",
        "Iron Ring",
        "Opal Ring",
        "Cerulean Ring",
        "Jet Ring",
    }
    PoeItemClassesToNames["Sceptre"] = []string{
        "Opal Sceptre",
        "Darkwood Sceptre",
        "Lead Sceptre",
        "Platinum Sceptre",
        "Crystal Sceptre",
        "Ochre Sceptre",
        "Tyrant's Sekhem",
        "Abyssal Sceptre",
        "Grinning Fetish",
        "Bronze Sceptre",
        "Shadow Sceptre",
        "Karui Sceptre",
        "Iron Sceptre",
        "Stag Sceptre",
        "Driftwood Sceptre",
        "Royal Sceptre",
        "Sambar Sceptre",
        "Quartz Sceptre",
        "Blood Sceptre",
        "Sekhem",
        "Void Sceptre",
        "Ritual Sceptre",
        "Vaal Sceptre",
        "Carnal Sceptre",
        "Horned Sceptre",
    }
    PoeItemClassesToNames["Shield"] = []string{
        "Ebony Tower Shield",
        "Studded Round Shield",
        "Pine Buckler",
        "Cedar Tower Shield",
        "Oak Buckler",
        "Splendid Round Shield",
        "Ezomyte Spiked Shield",
        "Pinnacle Tower Shield",
        "Painted Tower Shield",
        "Teak Round Shield",
        "Painted Buckler",
        "Bronze Tower Shield",
        "Rotted Round Shield",
        "Titanium Spirit Shield",
        "Yew Spirit Shield",
        "Reinforced Tower Shield",
        "Linden Kite Shield",
        "Burnished Spiked Shield",
        "Mosaic Kite Shield",
        "Ironwood Buckler",
        "Bone Spirit Shield",
        "Branded Kite Shield",
        "Supreme Spiked Shield",
        "Laminated Kite Shield",
        "Tarnished Spirit Shield",
        "Hammered Buckler",
        "Redwood Spiked Shield",
        "Ancient Spirit Shield",
        "Spiny Round Shield",
        "Crusader Buckler",
        "Plank Kite Shield",
        "Driftwood Spiked Shield",
        "Rawhide Tower Shield",
        "Twig Spirit Shield",
        "Maple Round Shield",
        "Archon Kite Shield",
        "Girded Tower Shield",
        "Enameled Buckler",
        "Gilded Buckler",
        "Etched Kite Shield",
        "Alloyed Spiked Shield",
        "Alder Spiked Shield",
        "Corrugated Buckler",
        "Crimson Round Shield",
        "Angelic Kite Shield",
        "Steel Kite Shield",
        "Fir Round Shield",
        "Reinforced Kite Shield",
        "Scarlet Round Shield",
        "Imperial Buckler",
        "Goathide Buckler",
        "Vaal Buckler",
        "Mahogany Tower Shield",
        "Champion Kite Shield",
        "Splintered Tower Shield",
        "Corroded Tower Shield",
        "Thorium Spirit Shield",
        "Baroque Round Shield",
        "Buckskin Tower Shield",
        "Elegant Round Shield",
        "Jingling Spirit Shield",
        "Polished Spiked Shield",
        "Crested Tower Shield",
        "Vaal Spirit Shield",
        "Harmonic Spirit Shield",
        "Walnut Spirit Shield",
        "Shagreen Tower Shield",
        "War Buckler",
        "Ivory Spirit Shield",
        "Lacewood Spirit Shield",
        "Cardinal Round Shield",
        "Sovereign Spiked Shield",
        "Chiming Spirit Shield",
        "Copper Tower Shield",
        "Ceremonial Kite Shield",
        "Spiked Round Shield",
        "Lacquered Buckler",
        "Fossilised Spirit Shield",
        "Golden Flame",
        "Spiked Bundle",
        "Brass Spirit Shield",
        "Mirrored Spiked Shield",
        "Colossal Tower Shield",
        "Ezomyte Tower Shield",
        "Ornate Spiked Shield",
        "Compound Spiked Shield",
        "Battle Buckler",
        "Layered Kite Shield",
        "Golden Buckler",
    }
    PoeItemClassesToNames["Staff"] = []string{
        "Lathi",
        "Highborn Staff",
        "Primitive Staff",
        "Long Staff",
        "Quarterstaff",
        "Gnarled Branch",
        "Crescent Staff",
        "Moon Staff",
        "Eclipse Staff",
        "Primordial Staff",
        "Imperial Staff",
        "Royal Staff",
        "Woodful Staff",
    }
    PoeItemClassesToNames["Two Hand Axe"] = []string{
        "Noble Axe",
        "Void Axe",
        "Despot Axe",
        "Headsman Axe",
        "Jasper Chopper",
        "Shadow Axe",
        "Vaal Axe",
        "Timber Axe",
        "Ezomyte Axe",
        "Talon Axe",
        "Sundering Axe",
        "Karui Chopper",
        "Stone Axe",
        "Jade Chopper",
        "Poleaxe",
        "Fleshripper",
        "Woodsplitter",
        "Gilded Axe",
        "Dagger Axe",
        "Labrys",
        "Abyssal Axe",
        "Double Axe",
    }
    PoeItemClassesToNames["Two Hand Mace"] = []string{
        "Driftwood Maul",
        "Meatgrinder",
        "Tribal Maul",
        "Colossus Mallet",
        "Solar Maul",
        "Spiny Maul",
        "Fright Maul",
        "Sledgehammer",
        "Totemic Maul",
        "Great Mallet",
        "Coronal Maul",
        "Jagged Maul",
        "Karui Maul",
        "Piledriver",
        "Plated Maul",
        "Imperial Maul",
        "Steelhead",
        "Morning Star",
        "Brass Maul",
        "Dread Maul",
        "Terror Maul",
        "Mallet",
    }
    PoeItemClassesToNames["Two Hand Sword"] = []string{
        "Keyblade",
        "Headman's Sword",
        "Tiger Sword",
        "Lion Sword",
        "Vaal Greatsword",
        "Butcher Sword",
        "Exquisite Blade",
        "Longsword",
        "Reaver Sword",
        "Spectral Sword",
        "Ezomyte Blade",
        "Highland Blade",
        "Two-Handed Sword",
        "Engraved Greatsword",
        "Etched Greatsword",
        "Ornate Sword",
        "Wraith Sword",
        "Footman Sword",
        "Corroded Blade",
        "Curved Blade",
        "Infernal Sword",
        "Lithe Blade",
        "Bastard Sword",
    }
    PoeItemClassesToNames["Wand"] = []string{
        "Convoking Wand",
        "Goat's Horn",
        "Quartz Wand",
        "Heathen Wand",
        "Imbued Wand",
        "Omen Wand",
        "Crystal Wand",
        "Profane Wand",
        "Driftwood Wand",
        "Carved Wand",
        "Faun's Horn",
        "Sage Wand",
        "Engraved Wand",
        "Pagan Wand",
        "Spiraled Wand",
        "Prophecy Wand",
        "Tornado Wand",
        "Demon's Horn",
        "Opal Wand",
        "Serpent Wand",
    }
    PoeItemClassesToNames["Warstaff"] = []string{
        "Coiled Staff",
        "Vile Staff",
        "Iron Staff",
        "Serpentine Staff",
        "Military Staff",
        "Judgement Staff",
        "Maelström Staff",
        "Foul Staff",
        "Ezomyte Staff",
    }
    for itemClass, itemNames := range PoeItemClassesToNames {
        for _, itemName := range itemNames {
            PoeItemNamesToClasses[itemName] = itemClass
        }
    }
}

