package stashvision

var poeItemClassesToNames = make(map[string][]string)
var poeItemNamesToClasses = make(map[string]string)

func init() {
    poeItemClassesToNames["Amulet"] = []string{
        "Hexclaw Talisman",
        "Lapis Amulet",
        "Jet Amulet",
        "Monkey Twins Talisman",
        "Ruby Amulet",
        "Primal Skull Talisman",
        "Fangjaw Talisman",
        "Deep One Talisman",
        "Deadhand Talisman",
        "Monkey Paw Talisman",
        "Avian Twins Talisman",
        "Black Maw Talisman",
        "Mandible Talisman",
        "Ashscale Talisman",
        "Jade Amulet",
        "Amber Amulet",
        "Chrysalis Talisman",
        "Bonespire Talisman",
        "Longtooth Talisman",
        "Breakrib Talisman",
        "Splitnewt Talisman",
        "Citrine Amulet",
        "Wereclaw Talisman",
        "Onyx Amulet",
        "Three Rat Talisman",
        "Marble Amulet",
        "Writhing Talisman",
        "Undying Flesh Talisman",
        "Gold Amulet",
        "Rotfeather Talisman",
        "Greatwolf Talisman",
        "Spinefuse Talisman",
        "Clutching Talisman",
        "Coral Amulet",
        "Blue Pearl Amulet",
        "Three Hands Talisman",
        "Rot Head Talisman",
        "Turquoise Amulet",
        "Horned Talisman",
        "Paua Amulet",
        "Lone Antler Talisman",
        "Agate Amulet",
    }
    poeItemClassesToNames["Belt"] = []string{
        "Rustic Sash",
        "Leather Belt",
        "Studded Belt",
        "Chain Belt",
        "Heavy Belt",
        "Crystal Belt",
        "Vanguard Belt",
        "Stygian Vise",
        "Cloth Belt",
        "Golden Obi",
    }
    poeItemClassesToNames["Boots"] = []string{
        "Arcanist Slippers",
        "Riveted Boots",
        "Reinforced Greaves",
        "Sorcerer Boots",
        "Slink Boots",
        "Wool Shoes",
        "Vaal Greaves",
        "Steel Greaves",
        "Carnal Boots",
        "Ancient Greaves",
        "Rawhide Boots",
        "Iron Greaves",
        "Antique Greaves",
        "Soldier Boots",
        "Titan Greaves",
        "Hydrascale Boots",
        "Conjurer Boots",
        "Samite Slippers",
        "Assassin's Boots",
        "Goathide Boots",
        "Two-Toned Boots",
        "Satin Slippers",
        "Legion Boots",
        "Velvet Slippers",
        "Wyrmscale Boots",
        "Mesh Boots",
        "Deerskin Boots",
        "Plated Greaves",
        "Zealot Boots",
        "Steelscale Boots",
        "Kaom's Greaves",
        "Shagreen Boots",
        "Sharkskin Boots",
        "Chain Boots",
        "Bronzescale Boots",
        "Murder Boots",
        "Nubuck Boots",
        "Eelskin Boots",
        "Shackled Boots",
        "Silk Slippers",
        "Wrapped Boots",
        "Golden Caligae",
        "Ambush Boots",
        "Crusader Boots",
        "Avian Slippers",
        "Trapper Boots",
        "Ringmail Boots",
        "Clasped Boots",
        "Goliath Greaves",
        "Ironscale Boots",
        "Strapped Boots",
        "Dragonscale Boots",
        "Leatherscale Boots",
        "Scholar Boots",
        "Stealth Boots",
        "Serpentscale Boots",
    }
    poeItemClassesToNames["Bow"] = []string{
        "Death Bow",
        "Composite Bow",
        "Sniper Bow",
        "Maraketh Bow",
        "Crude Bow",
        "Bone Bow",
        "Recurve Bow",
        "Ranger Bow",
        "Ivory Bow",
        "Thicket Bow",
        "Citadel Bow",
        "Steelwood Bow",
        "Decimation Bow",
        "Reflex Bow",
        "Imperial Bow",
        "Harbinger Bow",
        "Short Bow",
        "Decurve Bow",
        "Royal Bow",
        "Highborn Bow",
        "Long Bow",
        "Assassin Bow",
        "Spine Bow",
        "Compound Bow",
        "Grove Bow",
    }
    poeItemClassesToNames["Body Armour"] = []string{
        "Savant's Robe",
        "Majestic Plate",
        "Golden Mantle",
        "Mage's Vestment",
        "Colosseum Plate",
        "Saintly Chainmail",
        "General's Brigandine",
        "Holy Chainmail",
        "Vaal Regalia",
        "Sacrificial Garb",
        "Carnal Armour",
        "Destiny Leather",
        "Blood Raiment",
        "Quilted Jacket",
        "Latticed Ringmail",
        "Varnished Coat",
        "Scale Doublet",
        "Bronze Plate",
        "Glorious Leather",
        "Commander's Brigandine",
        "Crypt Armour",
        "Dragonscale Doublet",
        "Crusader Plate",
        "Plate Vest",
        "Sadist Garb",
        "Glorious Plate",
        "Devout Chainmail",
        "Oiled Coat",
        "Necromancer Silks",
        "War Plate",
        "Cabalist Regalia",
        "Assassin's Garb",
        "Scale Vest",
        "Field Lamellar",
        "Bone Armour",
        "Elegant Ringmail",
        "Sharkskin Tunic",
        "Crimson Raiment",
        "Copper Plate",
        "Thief's Garb",
        "Oiled Vest",
        "Silken Wrap",
        "Ringmail Coat",
        "Shabby Jerkin",
        "Infantry Brigandine",
        "Full Ringmail",
        "Golden Plate",
        "Hussar Brigandine",
        "Silken Vest",
        "Coronal Leather",
        "Wild Leather",
        "Chestplate",
        "Sleek Coat",
        "Conjurer's Vestment",
        "Lacquered Garb",
        "Chainmail Tunic",
        "Chainmail Doublet",
        "Occultist's Vestment",
        "Triumphant Lamellar",
        "Frontier Leather",
        "Arena Plate",
        "Wyrmscale Doublet",
        "Cutthroat's Garb",
        "Exquisite Leather",
        "Conquest Chainmail",
        "Sentinel Jacket",
        "Soldier's Brigandine",
        "Widowsilk Robe",
        "Full Scale Armour",
        "Full Chainmail",
        "Scholar's Robe",
        "Astral Plate",
        "Sun Plate",
        "Saint's Hauberk",
        "Battle Plate",
        "Sage's Robe",
        "Silken Garb",
        "Sun Leather",
        "Battle Lamellar",
        "Desert Brigandine",
        "Light Brigandine",
        "Ornate Ringmail",
        "Full Dragonscale",
        "Padded Vest",
        "Spidersilk Robe",
        "Chain Hauberk",
        "Strapped Leather",
        "Loricated Ringmail",
        "Simple Robe",
        "Eelskin Tunic",
        "Padded Jacket",
        "Full Wyrmscale",
        "Chainmail Vest",
        "Destroyer Regalia",
        "Full Leather",
        "Silk Robe",
        "Scarlet Raiment",
        "Lordly Plate",
        "Crusader Chainmail",
        "Full Plate",
        "Zodiac Leather",
        "Gladiator Plate",
        "Waxed Garb",
        "Buckskin Tunic",
        "Kaom's Plate",
    }
    poeItemClassesToNames["Claw"] = []string{
        "Timeworn Claw",
        "Tiger's Paw",
        "Cat's Paw",
        "Double Claw",
        "Sparkling Claw",
        "Awl",
        "Throat Stabber",
        "Fright Claw",
        "Vaal Claw",
        "Nailed Fist",
        "Great White Claw",
        "Gemini Claw",
        "Imperial Claw",
        "Terror Claw",
        "Gouger",
        "Twin Claw",
        "Blinder",
        "Noble Claw",
        "Hellion's Paw",
        "Gut Ripper",
        "Prehistoric Claw",
        "Sharktooth Claw",
        "Eye Gouger",
        "Eagle Claw",
        "Thresher Claw",
    }
    poeItemClassesToNames["Dagger"] = []string{
        "Skinning Knife",
        "Ethereal Blade",
        "Flaying Knife",
        "Gutting Knife",
        "Sai",
        "Prong Dagger",
        "Ambusher",
        "Stiletto",
        "Glass Shank",
        "Poignard",
        "Trisula",
    }
    poeItemClassesToNames["Gloves"] = []string{
        "Gripped Gloves",
        "Steel Gauntlets",
        "Fingerless Silk Gloves",
        "Embroidered Gloves",
        "Goathide Gloves",
        "Wrapped Mitts",
        "Assassin's Mitts",
        "Iron Gauntlets",
        "Vaal Gauntlets",
        "Shagreen Gloves",
        "Velvet Gloves",
        "Stealth Gloves",
        "Deerskin Gloves",
        "Ambush Mitts",
        "Mesh Gloves",
        "Clasped Mitts",
        "Crusader Gloves",
        "Nubuck Gloves",
        "Antique Gauntlets",
        "Silk Gloves",
        "Conjurer Gloves",
        "Titan Gauntlets",
        "Bronze Gauntlets",
        "Ringmail Gloves",
        "Sorcerer Gloves",
        "Serpentscale Gauntlets",
        "Fishscale Gauntlets",
        "Wyrmscale Gauntlets",
        "Plated Gauntlets",
        "Soldier Gloves",
        "Steelscale Gauntlets",
        "Hydrascale Gauntlets",
        "Legion Gloves",
        "Sharkskin Gloves",
        "Ironscale Gauntlets",
        "Slink Gloves",
        "Eelskin Gloves",
        "Carnal Mitts",
        "Zealot Gloves",
        "Arcanist Gloves",
        "Samite Gloves",
        "Dragonscale Gauntlets",
        "Satin Gloves",
        "Murder Mitts",
        "Riveted Gloves",
        "Golden Bracers",
        "Spiked Gloves",
        "Rawhide Gloves",
        "Goliath Gauntlets",
        "Trapper Mitts",
        "Chain Gloves",
        "Ancient Gauntlets",
        "Strapped Mitts",
        "Bronzescale Gauntlets",
        "Wool Gloves",
    }
    poeItemClassesToNames["Helmet"] = []string{
        "Hubris Circlet",
        "Regicide Mask",
        "Nightmare Bascinet",
        "Siege Helmet",
        "Sallet",
        "Samite Helmet",
        "Bone Helmet",
        "Plague Mask",
        "Solaris Circlet",
        "Wolf Pelt",
        "Gladiator Helmet",
        "Great Crown",
        "Fencer Helm",
        "Iron Circlet",
        "Eternal Burgonet",
        "Aventail Helmet",
        "Tricorne",
        "Iron Mask",
        "Vine Circlet",
        "Silken Hood",
        "Crusader Helmet",
        "Noble Tricorne",
        "Steel Circlet",
        "Fluted Bascinet",
        "Golden Mask",
        "Necromancer Circlet",
        "Prophet Crown",
        "Mind Cage",
        "Lion Pelt",
        "Cone Helmet",
        "Sinner Tricorne",
        "Raven Mask",
        "Harlequin Mask",
        "Secutor Helm",
        "Praetor Crown",
        "Close Helmet",
        "Royal Burgonet",
        "Gilded Sallet",
        "Lacquered Helmet",
        "Pig-Faced Bascinet",
        "Visored Sallet",
        "Soldier Helmet",
        "Golden Wreath",
        "Deicide Mask",
        "Ezomyte Burgonet",
        "Torture Cage",
        "Zealot Helmet",
        "Callous Mask",
        "Reaver Helmet",
        "Leather Hood",
        "Bone Circlet",
        "Festival Mask",
        "Barbute Helmet",
        "Great Helmet",
        "Magistrate Crown",
        "Tribal Circlet",
        "Scare Mask",
        "Lunaris Circlet",
        "Hunter Hood",
        "Leather Cap",
        "Ursine Pelt",
        "Rusted Coif",
        "Golden Visage",
        "Iron Hat",
        "Vaal Mask",
        "Battered Helm",
    }
    poeItemClassesToNames["One Hand Axe"] = []string{
        "Engraved Hatchet",
        "Chest Splitter",
        "Infernal Axe",
        "Karui Axe",
        "Broad Axe",
        "Spectral Axe",
        "Wrist Chopper",
        "War Axe",
        "Ceremonial Axe",
        "Wraith Axe",
        "Vaal Hatchet",
        "Cleaver",
        "Siege Axe",
        "Decorative Axe",
        "Runic Hatchet",
        "Arming Axe",
        "Boarding Axe",
        "Jasper Axe",
        "Tomahawk",
        "Etched Hatchet",
        "Jade Hatchet",
        "Reaver Axe",
        "Rusted Hatchet",
        "Royal Axe",
        "Butcher Axe",
    }
    poeItemClassesToNames["One Hand Mace"] = []string{
        "Pernarch",
        "Tenderizer",
        "Phantom Mace",
        "Bladed Mace",
        "Battle Hammer",
        "Ornate Mace",
        "Gavel",
        "Stone Hammer",
        "Dragon Mace",
        "Barbed Club",
        "Wyrm Mace",
        "Legion Hammer",
        "Auric Mace",
        "Rock Breaker",
        "Petrified Club",
        "Ceremonial Mace",
        "Nightmare Mace",
        "War Hammer",
        "Tribal Club",
        "Dream Mace",
        "Flanged Mace",
        "Behemoth Mace",
        "Driftwood Club",
        "Spiked Club",
        "Ancestral Club",
    }
    poeItemClassesToNames["One Hand Sword"] = []string{
        "Copper Sword",
        "Gladius",
        "Hook Sword",
        "Tiger Hook",
        "Battle Sword",
        "Ancient Sword",
        "Dusk Blade",
        "Broad Sword",
        "Twilight Blade",
        "War Sword",
        "Gemstone Sword",
        "Eternal Sword",
        "Elder Sword",
        "Graceful Sword",
        "Charan's Sword",
        "Cutlass",
        "Corsair Sword",
        "Baselard",
        "Rusted Sword",
        "Legion Sword",
        "Variscite Blade",
        "Elegant Sword",
        "Sabre",
        "Midnight Blade",
        "Grappler",
        "Vaal Blade",
    }
    poeItemClassesToNames["Quiver"] = []string{
        "Fire Arrow Quiver",
        "Serrated Arrow Quiver",
        "Blunt Arrow Quiver",
        "Sharktooth Arrow Quiver",
        "Rugged Quiver",
        "Spike-Point Arrow Quiver",
        "Cured Quiver",
        "Light Quiver",
        "Conductive Quiver",
        "Broadhead Arrow Quiver",
        "Penetrating Arrow Quiver",
        "Two-Point Arrow Quiver",
        "Ornate Quiver",
        "Heavy Quiver",
    }
    poeItemClassesToNames["Ring"] = []string{
        "Sapphire Ring",
        "Two-Stone Ring",
        "Topaz Ring",
        "Ruby Ring",
        "Iron Ring",
        "Prismatic Ring",
        "Jet Ring",
        "Moonstone Ring",
        "Coral Ring",
        "Amethyst Ring",
        "Steel Ring",
        "Unset Ring",
        "Paua Ring",
        "Diamond Ring",
        "Breach Ring",
        "Golden Hoop",
        "Gold Ring",
        "Cerulean Ring",
        "Opal Ring",
        "Vermillion Ring",
    }
    poeItemClassesToNames["Rune Dagger"] = []string{
        "Demon Dagger",
        "Imp Dagger",
        "Imperial Skean",
        "Boot Blade",
        "Slaughter Knife",
        "Boot Knife",
        "Butcher Knife",
        "Ezomyte Dagger",
        "Carving Knife",
        "Fiend Dagger",
        "Platinum Kris",
        "Skean",
        "Golden Kris",
        "Royal Skean",
        "Copper Kris",
    }
    poeItemClassesToNames["Sceptre"] = []string{
        "Sekhem",
        "Shadow Sceptre",
        "Horned Sceptre",
        "Ritual Sceptre",
        "Quartz Sceptre",
        "Bronze Sceptre",
        "Darkwood Sceptre",
        "Blood Sceptre",
        "Lead Sceptre",
        "Carnal Sceptre",
        "Crystal Sceptre",
        "Grinning Fetish",
        "Sambar Sceptre",
        "Tyrant's Sekhem",
        "Driftwood Sceptre",
        "Ochre Sceptre",
        "Void Sceptre",
        "Royal Sceptre",
        "Stag Sceptre",
        "Opal Sceptre",
        "Abyssal Sceptre",
        "Platinum Sceptre",
        "Karui Sceptre",
        "Vaal Sceptre",
        "Iron Sceptre",
    }
    poeItemClassesToNames["Shield"] = []string{
        "Painted Tower Shield",
        "Imperial Buckler",
        "Bronze Tower Shield",
        "Ezomyte Tower Shield",
        "Splendid Round Shield",
        "Copper Tower Shield",
        "Buckskin Tower Shield",
        "Teak Round Shield",
        "Rawhide Tower Shield",
        "Angelic Kite Shield",
        "Pinnacle Tower Shield",
        "Laminated Kite Shield",
        "Champion Kite Shield",
        "Colossal Tower Shield",
        "Thorium Spirit Shield",
        "Harmonic Spirit Shield",
        "Scarlet Round Shield",
        "Brass Spirit Shield",
        "Compound Spiked Shield",
        "Ironwood Buckler",
        "Supreme Spiked Shield",
        "Mosaic Kite Shield",
        "Rotted Round Shield",
        "Etched Kite Shield",
        "Lacewood Spirit Shield",
        "Ivory Spirit Shield",
        "Chiming Spirit Shield",
        "Fir Round Shield",
        "Spiny Round Shield",
        "Golden Buckler",
        "Mirrored Spiked Shield",
        "Plank Kite Shield",
        "Battle Buckler",
        "Sovereign Spiked Shield",
        "Crusader Buckler",
        "Reinforced Tower Shield",
        "Walnut Spirit Shield",
        "Cedar Tower Shield",
        "Crested Tower Shield",
        "Studded Round Shield",
        "Yew Spirit Shield",
        "War Buckler",
        "Vaal Spirit Shield",
        "Corroded Tower Shield",
        "Redwood Spiked Shield",
        "Pine Buckler",
        "Bone Spirit Shield",
        "Maple Round Shield",
        "Gilded Buckler",
        "Alder Spiked Shield",
        "Fossilised Spirit Shield",
        "Branded Kite Shield",
        "Shagreen Tower Shield",
        "Archon Kite Shield",
        "Corrugated Buckler",
        "Mahogany Tower Shield",
        "Steel Kite Shield",
        "Ceremonial Kite Shield",
        "Goathide Buckler",
        "Tarnished Spirit Shield",
        "Baroque Round Shield",
        "Ancient Spirit Shield",
        "Vaal Buckler",
        "Linden Kite Shield",
        "Reinforced Kite Shield",
        "Spiked Bundle",
        "Alloyed Spiked Shield",
        "Twig Spirit Shield",
        "Spiked Round Shield",
        "Layered Kite Shield",
        "Oak Buckler",
        "Lacquered Buckler",
        "Cardinal Round Shield",
        "Enameled Buckler",
        "Ornate Spiked Shield",
        "Titanium Spirit Shield",
        "Polished Spiked Shield",
        "Painted Buckler",
        "Jingling Spirit Shield",
        "Girded Tower Shield",
        "Golden Flame",
        "Ezomyte Spiked Shield",
        "Splintered Tower Shield",
        "Elegant Round Shield",
        "Ebony Tower Shield",
        "Hammered Buckler",
        "Driftwood Spiked Shield",
        "Crimson Round Shield",
        "Burnished Spiked Shield",
    }
    poeItemClassesToNames["Staff"] = []string{
        "Gnarled Branch",
        "Primordial Staff",
        "Lathi",
        "Primitive Staff",
        "Long Staff",
        "Royal Staff",
        "Woodful Staff",
        "Crescent Staff",
        "Highborn Staff",
        "Moon Staff",
        "Eclipse Staff",
        "Quarterstaff",
        "Imperial Staff",
    }
    poeItemClassesToNames["Two Hand Axe"] = []string{
        "Stone Axe",
        "Sundering Axe",
        "Double Axe",
        "Jasper Chopper",
        "Dagger Axe",
        "Fleshripper",
        "Headsman Axe",
        "Timber Axe",
        "Gilded Axe",
        "Talon Axe",
        "Woodsplitter",
        "Jade Chopper",
        "Noble Axe",
        "Void Axe",
        "Labrys",
        "Poleaxe",
        "Ezomyte Axe",
        "Shadow Axe",
        "Abyssal Axe",
        "Vaal Axe",
        "Karui Chopper",
        "Despot Axe",
    }
    poeItemClassesToNames["Two Hand Mace"] = []string{
        "Tribal Maul",
        "Piledriver",
        "Great Mallet",
        "Meatgrinder",
        "Karui Maul",
        "Brass Maul",
        "Colossus Mallet",
        "Fright Maul",
        "Mallet",
        "Solar Maul",
        "Jagged Maul",
        "Dread Maul",
        "Driftwood Maul",
        "Terror Maul",
        "Totemic Maul",
        "Morning Star",
        "Plated Maul",
        "Steelhead",
        "Imperial Maul",
        "Spiny Maul",
        "Coronal Maul",
        "Sledgehammer",
    }
    poeItemClassesToNames["Two Hand Sword"] = []string{
        "Corroded Blade",
        "Lithe Blade",
        "Exquisite Blade",
        "Wraith Sword",
        "Vaal Greatsword",
        "Bastard Sword",
        "Infernal Sword",
        "Tiger Sword",
        "Footman Sword",
        "Etched Greatsword",
        "Engraved Greatsword",
        "Highland Blade",
        "Ezomyte Blade",
        "Headman's Sword",
        "Butcher Sword",
        "Two-Handed Sword",
        "Curved Blade",
        "Reaver Sword",
        "Ornate Sword",
        "Longsword",
        "Spectral Sword",
        "Keyblade",
        "Lion Sword",
    }
    poeItemClassesToNames["Wand"] = []string{
        "Prophecy Wand",
        "Carved Wand",
        "Convoking Wand",
        "Demon's Horn",
        "Sage Wand",
        "Driftwood Wand",
        "Faun's Horn",
        "Tornado Wand",
        "Profane Wand",
        "Goat's Horn",
        "Heathen Wand",
        "Opal Wand",
        "Engraved Wand",
        "Crystal Wand",
        "Pagan Wand",
        "Imbued Wand",
        "Serpent Wand",
        "Quartz Wand",
        "Omen Wand",
        "Spiraled Wand",
    }
    poeItemClassesToNames["Warstaff"] = []string{
        "Iron Staff",
        "Coiled Staff",
        "Serpentine Staff",
        "Vile Staff",
        "Military Staff",
        "Judgement Staff",
        "Ezomyte Staff",
        "Maelström Staff",
        "Foul Staff",
    }
    for itemClass, itemNames := range poeItemClassesToNames {
        for _, itemName := range itemNames {
            poeItemNamesToClasses[itemName] = itemClass
        }
    }
}

