package stashvision

var poeItemClassesToNames = make(map[string][]string)
var poeItemNamesToClasses = make(map[string]string)

func init() {
    poeItemClassesToNames["Amulet"] = []string{
        "Writhing Talisman",
        "Deadhand Talisman",
        "Chrysalis Talisman",
        "Agate Amulet",
        "Citrine Amulet",
        "Fangjaw Talisman",
        "Hexclaw Talisman",
        "Horned Talisman",
        "Monkey Twins Talisman",
        "Primal Skull Talisman",
        "Three Hands Talisman",
        "Bonespire Talisman",
        "Lone Antler Talisman",
        "Marble Amulet",
        "Mandible Talisman",
        "Clutching Talisman",
        "Avian Twins Talisman",
        "Rotfeather Talisman",
        "Ruby Amulet",
        "Gold Amulet",
        "Three Rat Talisman",
        "Jade Amulet",
        "Black Maw Talisman",
        "Turquoise Amulet",
        "Greatwolf Talisman",
        "Jet Amulet",
        "Blue Pearl Amulet",
        "Coral Amulet",
        "Splitnewt Talisman",
        "Spinefuse Talisman",
        "Deep One Talisman",
        "Longtooth Talisman",
        "Undying Flesh Talisman",
        "Ashscale Talisman",
        "Rot Head Talisman",
        "Monkey Paw Talisman",
        "Amber Amulet",
        "Lapis Amulet",
        "Breakrib Talisman",
        "Wereclaw Talisman",
        "Paua Amulet",
        "Onyx Amulet",
    }
    poeItemClassesToNames["Belt"] = []string{
        "Vanguard Belt",
        "Chain Belt",
        "Rustic Sash",
        "Leather Belt",
        "Stygian Vise",
        "Crystal Belt",
        "Cloth Belt",
        "Golden Obi",
        "Heavy Belt",
        "Studded Belt",
    }
    poeItemClassesToNames["Boots"] = []string{
        "Rawhide Boots",
        "Carnal Boots",
        "Murder Boots",
        "Wrapped Boots",
        "Arcanist Slippers",
        "Leatherscale Boots",
        "Ringmail Boots",
        "Strapped Boots",
        "Chain Boots",
        "Deerskin Boots",
        "Steelscale Boots",
        "Serpentscale Boots",
        "Nubuck Boots",
        "Soldier Boots",
        "Zealot Boots",
        "Scholar Boots",
        "Mesh Boots",
        "Shackled Boots",
        "Slink Boots",
        "Shagreen Boots",
        "Kaom's Greaves",
        "Eelskin Boots",
        "Ancient Greaves",
        "Wool Shoes",
        "Bronzescale Boots",
        "Titan Greaves",
        "Goathide Boots",
        "Goliath Greaves",
        "Steel Greaves",
        "Assassin's Boots",
        "Satin Slippers",
        "Antique Greaves",
        "Legion Boots",
        "Reinforced Greaves",
        "Samite Slippers",
        "Conjurer Boots",
        "Vaal Greaves",
        "Ambush Boots",
        "Velvet Slippers",
        "Sorcerer Boots",
        "Two-Toned Boots",
        "Dragonscale Boots",
        "Ironscale Boots",
        "Plated Greaves",
        "Avian Slippers",
        "Trapper Boots",
        "Wyrmscale Boots",
        "Hydrascale Boots",
        "Clasped Boots",
        "Crusader Boots",
        "Golden Caligae",
        "Stealth Boots",
        "Silk Slippers",
        "Iron Greaves",
        "Sharkskin Boots",
        "Riveted Boots",
    }
    poeItemClassesToNames["Bow"] = []string{
        "Grove Bow",
        "Compound Bow",
        "Short Bow",
        "Decurve Bow",
        "Steelwood Bow",
        "Maraketh Bow",
        "Bone Bow",
        "Harbinger Bow",
        "Recurve Bow",
        "Reflex Bow",
        "Ivory Bow",
        "Decimation Bow",
        "Thicket Bow",
        "Citadel Bow",
        "Ranger Bow",
        "Composite Bow",
        "Crude Bow",
        "Royal Bow",
        "Imperial Bow",
        "Long Bow",
        "Sniper Bow",
        "Highborn Bow",
        "Spine Bow",
        "Death Bow",
        "Assassin Bow",
    }
    poeItemClassesToNames["Body Armour"] = []string{
        "Copper Plate",
        "Padded Vest",
        "Sun Plate",
        "Coronal Leather",
        "Zodiac Leather",
        "Holy Chainmail",
        "Glorious Leather",
        "Infantry Brigandine",
        "Sentinel Jacket",
        "Silken Wrap",
        "Golden Mantle",
        "Colosseum Plate",
        "Eelskin Tunic",
        "Scale Doublet",
        "Blood Raiment",
        "Devout Chainmail",
        "Silk Robe",
        "Widowsilk Robe",
        "Chestplate",
        "Wild Leather",
        "Scholar's Robe",
        "Full Plate",
        "Occultist's Vestment",
        "Full Dragonscale",
        "Sleek Coat",
        "Latticed Ringmail",
        "Triumphant Lamellar",
        "Kaom's Plate",
        "Crimson Raiment",
        "Sun Leather",
        "Cabalist Regalia",
        "War Plate",
        "Lacquered Garb",
        "Field Lamellar",
        "Soldier's Brigandine",
        "Silken Vest",
        "Elegant Ringmail",
        "Sacrificial Garb",
        "Sharkskin Tunic",
        "Wyrmscale Doublet",
        "Glorious Plate",
        "Mage's Vestment",
        "Sage's Robe",
        "Astral Plate",
        "Buckskin Tunic",
        "Oiled Vest",
        "Hussar Brigandine",
        "Light Brigandine",
        "Commander's Brigandine",
        "Lordly Plate",
        "Battle Lamellar",
        "Full Leather",
        "Plate Vest",
        "Full Ringmail",
        "Carnal Armour",
        "Scale Vest",
        "Bronze Plate",
        "Ringmail Coat",
        "Conjurer's Vestment",
        "Varnished Coat",
        "Shabby Jerkin",
        "Vaal Regalia",
        "Destiny Leather",
        "Full Scale Armour",
        "Chain Hauberk",
        "Saintly Chainmail",
        "Bone Armour",
        "Scarlet Raiment",
        "Golden Plate",
        "Quilted Jacket",
        "Frontier Leather",
        "Desert Brigandine",
        "Waxed Garb",
        "Spidersilk Robe",
        "Silken Garb",
        "Assassin's Garb",
        "Crusader Chainmail",
        "Necromancer Silks",
        "Oiled Coat",
        "Ornate Ringmail",
        "Chainmail Doublet",
        "Full Chainmail",
        "Simple Robe",
        "Strapped Leather",
        "Savant's Robe",
        "Saint's Hauberk",
        "Thief's Garb",
        "Battle Plate",
        "Crypt Armour",
        "Exquisite Leather",
        "Chainmail Vest",
        "Dragonscale Doublet",
        "Gladiator Plate",
        "Arena Plate",
        "Loricated Ringmail",
        "General's Brigandine",
        "Cutthroat's Garb",
        "Majestic Plate",
        "Destroyer Regalia",
        "Padded Jacket",
        "Chainmail Tunic",
        "Crusader Plate",
        "Conquest Chainmail",
        "Full Wyrmscale",
        "Sadist Garb",
    }
    poeItemClassesToNames["Claw"] = []string{
        "Twin Claw",
        "Eagle Claw",
        "Vaal Claw",
        "Prehistoric Claw",
        "Imperial Claw",
        "Throat Stabber",
        "Cat's Paw",
        "Double Claw",
        "Gut Ripper",
        "Sharktooth Claw",
        "Gemini Claw",
        "Eye Gouger",
        "Noble Claw",
        "Tiger's Paw",
        "Terror Claw",
        "Timeworn Claw",
        "Great White Claw",
        "Hellion's Paw",
        "Thresher Claw",
        "Fright Claw",
        "Blinder",
        "Awl",
        "Sparkling Claw",
        "Gouger",
        "Nailed Fist",
    }
    poeItemClassesToNames["Dagger"] = []string{
        "Flaying Knife",
        "Prong Dagger",
        "Sai",
        "Glass Shank",
        "Poignard",
        "Trisula",
        "Stiletto",
        "Gutting Knife",
        "Ambusher",
        "Skinning Knife",
        "Ethereal Blade",
    }
    poeItemClassesToNames["Gloves"] = []string{
        "Hydrascale Gauntlets",
        "Dragonscale Gauntlets",
        "Rawhide Gloves",
        "Wyrmscale Gauntlets",
        "Samite Gloves",
        "Chain Gloves",
        "Ambush Mitts",
        "Sharkskin Gloves",
        "Titan Gauntlets",
        "Spiked Gloves",
        "Mesh Gloves",
        "Fishscale Gauntlets",
        "Steel Gauntlets",
        "Zealot Gloves",
        "Goliath Gauntlets",
        "Satin Gloves",
        "Embroidered Gloves",
        "Bronze Gauntlets",
        "Golden Bracers",
        "Bronzescale Gauntlets",
        "Eelskin Gloves",
        "Ancient Gauntlets",
        "Goathide Gloves",
        "Assassin's Mitts",
        "Antique Gauntlets",
        "Riveted Gloves",
        "Strapped Mitts",
        "Slink Gloves",
        "Deerskin Gloves",
        "Ironscale Gauntlets",
        "Clasped Mitts",
        "Trapper Mitts",
        "Sorcerer Gloves",
        "Stealth Gloves",
        "Ringmail Gloves",
        "Fingerless Silk Gloves",
        "Carnal Mitts",
        "Silk Gloves",
        "Crusader Gloves",
        "Murder Mitts",
        "Wrapped Mitts",
        "Velvet Gloves",
        "Shagreen Gloves",
        "Wool Gloves",
        "Conjurer Gloves",
        "Plated Gauntlets",
        "Steelscale Gauntlets",
        "Vaal Gauntlets",
        "Arcanist Gloves",
        "Nubuck Gloves",
        "Serpentscale Gauntlets",
        "Legion Gloves",
        "Soldier Gloves",
        "Gripped Gloves",
        "Iron Gauntlets",
    }
    poeItemClassesToNames["Helmet"] = []string{
        "Iron Mask",
        "Raven Mask",
        "Harlequin Mask",
        "Pig-Faced Bascinet",
        "Regicide Mask",
        "Hunter Hood",
        "Crusader Helmet",
        "Torture Cage",
        "Visored Sallet",
        "Lacquered Helmet",
        "Festival Mask",
        "Praetor Crown",
        "Sallet",
        "Silken Hood",
        "Callous Mask",
        "Fencer Helm",
        "Steel Circlet",
        "Sinner Tricorne",
        "Vine Circlet",
        "Necromancer Circlet",
        "Scare Mask",
        "Leather Cap",
        "Solaris Circlet",
        "Great Crown",
        "Zealot Helmet",
        "Lion Pelt",
        "Soldier Helmet",
        "Lunaris Circlet",
        "Vaal Mask",
        "Mind Cage",
        "Close Helmet",
        "Prophet Crown",
        "Gilded Sallet",
        "Siege Helmet",
        "Bone Circlet",
        "Bone Helmet",
        "Eternal Burgonet",
        "Golden Mask",
        "Nightmare Bascinet",
        "Aventail Helmet",
        "Magistrate Crown",
        "Barbute Helmet",
        "Battered Helm",
        "Fluted Bascinet",
        "Rusted Coif",
        "Tribal Circlet",
        "Great Helmet",
        "Wolf Pelt",
        "Deicide Mask",
        "Secutor Helm",
        "Cone Helmet",
        "Golden Wreath",
        "Ursine Pelt",
        "Gladiator Helmet",
        "Plague Mask",
        "Royal Burgonet",
        "Iron Hat",
        "Samite Helmet",
        "Hubris Circlet",
        "Ezomyte Burgonet",
        "Leather Hood",
        "Noble Tricorne",
        "Iron Circlet",
        "Reaver Helmet",
        "Golden Visage",
        "Tricorne",
    }
    poeItemClassesToNames["One Hand Axe"] = []string{
        "Vaal Hatchet",
        "War Axe",
        "Jade Hatchet",
        "Etched Hatchet",
        "Infernal Axe",
        "Broad Axe",
        "Arming Axe",
        "Tomahawk",
        "Wraith Axe",
        "Ceremonial Axe",
        "Engraved Hatchet",
        "Spectral Axe",
        "Runic Hatchet",
        "Boarding Axe",
        "Karui Axe",
        "Butcher Axe",
        "Royal Axe",
        "Cleaver",
        "Siege Axe",
        "Wrist Chopper",
        "Rusted Hatchet",
        "Decorative Axe",
        "Jasper Axe",
        "Chest Splitter",
        "Reaver Axe",
    }
    poeItemClassesToNames["One Hand Mace"] = []string{
        "Rock Breaker",
        "Behemoth Mace",
        "Flanged Mace",
        "Nightmare Mace",
        "Petrified Club",
        "Ancestral Club",
        "Gavel",
        "Pernarch",
        "Stone Hammer",
        "War Hammer",
        "Bladed Mace",
        "Dream Mace",
        "Auric Mace",
        "Phantom Mace",
        "Ceremonial Mace",
        "Tenderizer",
        "Barbed Club",
        "Dragon Mace",
        "Battle Hammer",
        "Wyrm Mace",
        "Legion Hammer",
        "Driftwood Club",
        "Tribal Club",
        "Ornate Mace",
        "Spiked Club",
    }
    poeItemClassesToNames["One Hand Sword"] = []string{
        "Gemstone Sword",
        "Copper Sword",
        "Grappler",
        "Corsair Sword",
        "Charan's Sword",
        "Broad Sword",
        "Variscite Blade",
        "Battle Sword",
        "Cutlass",
        "Dusk Blade",
        "Tiger Hook",
        "Midnight Blade",
        "Sabre",
        "Hook Sword",
        "Legion Sword",
        "Vaal Blade",
        "Twilight Blade",
        "Rusted Sword",
        "Gladius",
        "War Sword",
        "Elegant Sword",
        "Eternal Sword",
        "Graceful Sword",
        "Elder Sword",
        "Baselard",
        "Ancient Sword",
    }
    poeItemClassesToNames["Quiver"] = []string{
        "Serrated Arrow Quiver",
        "Fire Arrow Quiver",
        "Spike-Point Arrow Quiver",
        "Ornate Quiver",
        "Conductive Quiver",
        "Rugged Quiver",
        "Light Quiver",
        "Heavy Quiver",
        "Two-Point Arrow Quiver",
        "Cured Quiver",
        "Blunt Arrow Quiver",
        "Penetrating Arrow Quiver",
        "Sharktooth Arrow Quiver",
        "Broadhead Arrow Quiver",
    }
    poeItemClassesToNames["Ring"] = []string{
        "Coral Ring",
        "Two-Stone Ring",
        "Paua Ring",
        "Sapphire Ring",
        "Diamond Ring",
        "Iron Ring",
        "Cerulean Ring",
        "Breach Ring",
        "Unset Ring",
        "Prismatic Ring",
        "Jet Ring",
        "Ruby Ring",
        "Steel Ring",
        "Topaz Ring",
        "Amethyst Ring",
        "Opal Ring",
        "Vermillion Ring",
        "Gold Ring",
        "Moonstone Ring",
        "Golden Hoop",
    }
    poeItemClassesToNames["Rune Dagger"] = []string{
        "Butcher Knife",
        "Platinum Kris",
        "Boot Blade",
        "Imperial Skean",
        "Ezomyte Dagger",
        "Demon Dagger",
        "Carving Knife",
        "Skean",
        "Fiend Dagger",
        "Royal Skean",
        "Copper Kris",
        "Imp Dagger",
        "Golden Kris",
        "Slaughter Knife",
        "Boot Knife",
    }
    poeItemClassesToNames["Sceptre"] = []string{
        "Opal Sceptre",
        "Ritual Sceptre",
        "Driftwood Sceptre",
        "Abyssal Sceptre",
        "Stag Sceptre",
        "Karui Sceptre",
        "Iron Sceptre",
        "Sambar Sceptre",
        "Crystal Sceptre",
        "Platinum Sceptre",
        "Tyrant's Sekhem",
        "Shadow Sceptre",
        "Darkwood Sceptre",
        "Royal Sceptre",
        "Vaal Sceptre",
        "Horned Sceptre",
        "Carnal Sceptre",
        "Quartz Sceptre",
        "Grinning Fetish",
        "Bronze Sceptre",
        "Ochre Sceptre",
        "Blood Sceptre",
        "Sekhem",
        "Void Sceptre",
        "Lead Sceptre",
    }
    poeItemClassesToNames["Shield"] = []string{
        "Ornate Spiked Shield",
        "Steel Kite Shield",
        "Cedar Tower Shield",
        "Walnut Spirit Shield",
        "Archon Kite Shield",
        "Alloyed Spiked Shield",
        "Ebony Tower Shield",
        "Vaal Spirit Shield",
        "Branded Kite Shield",
        "Rawhide Tower Shield",
        "Enameled Buckler",
        "Crusader Buckler",
        "Pine Buckler",
        "Ezomyte Tower Shield",
        "Etched Kite Shield",
        "Lacquered Buckler",
        "Studded Round Shield",
        "Splendid Round Shield",
        "Jingling Spirit Shield",
        "Fir Round Shield",
        "Ironwood Buckler",
        "Splintered Tower Shield",
        "Crimson Round Shield",
        "Chiming Spirit Shield",
        "Maple Round Shield",
        "Ceremonial Kite Shield",
        "Vaal Buckler",
        "Cardinal Round Shield",
        "Titanium Spirit Shield",
        "Mosaic Kite Shield",
        "Shagreen Tower Shield",
        "Battle Buckler",
        "Gilded Buckler",
        "Champion Kite Shield",
        "Pinnacle Tower Shield",
        "Crested Tower Shield",
        "Thorium Spirit Shield",
        "Twig Spirit Shield",
        "Reinforced Kite Shield",
        "Reinforced Tower Shield",
        "Painted Tower Shield",
        "Copper Tower Shield",
        "Brass Spirit Shield",
        "Mirrored Spiked Shield",
        "Spiny Round Shield",
        "Buckskin Tower Shield",
        "Hammered Buckler",
        "Oak Buckler",
        "Tarnished Spirit Shield",
        "Supreme Spiked Shield",
        "Fossilised Spirit Shield",
        "Angelic Kite Shield",
        "Golden Flame",
        "Laminated Kite Shield",
        "Linden Kite Shield",
        "Baroque Round Shield",
        "War Buckler",
        "Goathide Buckler",
        "Corrugated Buckler",
        "Bone Spirit Shield",
        "Girded Tower Shield",
        "Colossal Tower Shield",
        "Mahogany Tower Shield",
        "Rotted Round Shield",
        "Polished Spiked Shield",
        "Compound Spiked Shield",
        "Harmonic Spirit Shield",
        "Plank Kite Shield",
        "Sovereign Spiked Shield",
        "Bronze Tower Shield",
        "Golden Buckler",
        "Painted Buckler",
        "Corroded Tower Shield",
        "Scarlet Round Shield",
        "Imperial Buckler",
        "Spiked Round Shield",
        "Teak Round Shield",
        "Ivory Spirit Shield",
        "Burnished Spiked Shield",
        "Driftwood Spiked Shield",
        "Ezomyte Spiked Shield",
        "Redwood Spiked Shield",
        "Spiked Bundle",
        "Ancient Spirit Shield",
        "Elegant Round Shield",
        "Yew Spirit Shield",
        "Lacewood Spirit Shield",
        "Alder Spiked Shield",
        "Layered Kite Shield",
    }
    poeItemClassesToNames["Staff"] = []string{
        "Gnarled Branch",
        "Crescent Staff",
        "Primitive Staff",
        "Quarterstaff",
        "Eclipse Staff",
        "Primordial Staff",
        "Highborn Staff",
        "Woodful Staff",
        "Long Staff",
        "Imperial Staff",
        "Moon Staff",
        "Royal Staff",
        "Lathi",
    }
    poeItemClassesToNames["Thrusting One Hand Sword"] = []string{
        "Serrated Foil",
        "Estoc",
        "Tempered Foil",
        "Battered Foil",
        "Antique Rapier",
        "Harpy Rapier",
        "Basket Rapier",
        "Thorn Rapier",
        "Dragoon Sword",
        "Dragonbone Rapier",
        "Spiraled Foil",
        "Fancy Foil",
        "Courtesan Sword",
        "Vaal Rapier",
        "Jewelled Foil",
        "Burnished Foil",
        "Primeval Rapier",
        "Elegant Foil",
        "Rusted Spike",
        "Smallsword",
        "Jagged Foil",
        "Wyrmbone Rapier",
        "Apex Rapier",
        "Whalebone Rapier",
        "Pecoraro",
    }
    poeItemClassesToNames["Two Hand Axe"] = []string{
        "Noble Axe",
        "Headsman Axe",
        "Dagger Axe",
        "Jade Chopper",
        "Void Axe",
        "Karui Chopper",
        "Poleaxe",
        "Labrys",
        "Ezomyte Axe",
        "Despot Axe",
        "Sundering Axe",
        "Fleshripper",
        "Stone Axe",
        "Abyssal Axe",
        "Woodsplitter",
        "Gilded Axe",
        "Shadow Axe",
        "Double Axe",
        "Talon Axe",
        "Vaal Axe",
        "Timber Axe",
        "Jasper Chopper",
    }
    poeItemClassesToNames["Two Hand Mace"] = []string{
        "Solar Maul",
        "Karui Maul",
        "Jagged Maul",
        "Meatgrinder",
        "Mallet",
        "Great Mallet",
        "Fright Maul",
        "Tribal Maul",
        "Steelhead",
        "Coronal Maul",
        "Driftwood Maul",
        "Morning Star",
        "Dread Maul",
        "Totemic Maul",
        "Sledgehammer",
        "Terror Maul",
        "Brass Maul",
        "Colossus Mallet",
        "Plated Maul",
        "Spiny Maul",
        "Piledriver",
        "Imperial Maul",
    }
    poeItemClassesToNames["Two Hand Sword"] = []string{
        "Highland Blade",
        "Headman's Sword",
        "Ezomyte Blade",
        "Longsword",
        "Keyblade",
        "Infernal Sword",
        "Two-Handed Sword",
        "Vaal Greatsword",
        "Lion Sword",
        "Engraved Greatsword",
        "Reaver Sword",
        "Spectral Sword",
        "Tiger Sword",
        "Lithe Blade",
        "Wraith Sword",
        "Ornate Sword",
        "Butcher Sword",
        "Curved Blade",
        "Corroded Blade",
        "Exquisite Blade",
        "Etched Greatsword",
        "Footman Sword",
        "Bastard Sword",
    }
    poeItemClassesToNames["Wand"] = []string{
        "Quartz Wand",
        "Crystal Wand",
        "Heathen Wand",
        "Convoking Wand",
        "Omen Wand",
        "Demon's Horn",
        "Carved Wand",
        "Spiraled Wand",
        "Tornado Wand",
        "Serpent Wand",
        "Driftwood Wand",
        "Engraved Wand",
        "Goat's Horn",
        "Imbued Wand",
        "Opal Wand",
        "Faun's Horn",
        "Prophecy Wand",
        "Pagan Wand",
        "Sage Wand",
        "Profane Wand",
    }
    poeItemClassesToNames["Warstaff"] = []string{
        "Iron Staff",
        "Foul Staff",
        "Vile Staff",
        "Maelström Staff",
        "Military Staff",
        "Ezomyte Staff",
        "Serpentine Staff",
        "Judgement Staff",
        "Coiled Staff",
    }
    for itemClass, itemNames := range poeItemClassesToNames {
        for _, itemName := range itemNames {
            poeItemNamesToClasses[itemName] = itemClass
        }
    }
}

