name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v cmd/stashvision.go
      env:
        GOOS: windows
        GOARCH: amd64
      working-directory: ./stashvision-go
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: stashvision.exe
        path: stashvision-go/stashvision.exe
